### ISSUE TITLE
Sign Language Dataset

### ISSUE THREAD

**Issue by mr-ubik** [MrEliptik/HandPose#2]
Have you considered adding and testing a Sign Language Dataset?
PS: Fantastic work!

**Comment by MrEliptik** [comment]
My current goal is to make a v2 in order to get better detection and faster runtime. Right now the detection is quite capricious and if the pose you make is too complicated, it may not be recognized as a hand at all.
The data has to be greatly improved as it's highly biased for now, considering only my right hand was used to train the different poses.
The challenge with Sign language will be the speed at which the person signs. And even though the signs are recognized correctly, you would then have to process them to get the meaning. It's not impossible but definitely challenging.  

To really reply to your question, I'll think about adding specific signs to the training in the next version. In the mean time, I'm open to contribution and I would love to collaborate with people on something like this!

PS: Thanks a lot!
